### PR TITLE
fix: removed bg

### LINKED ISSUE #5: Logo with background
I was creating a PR to https://github.com/openjs-foundation/artwork to add the fastify logos

But I found that the files:

- fastify-1000px-square-01.png
- fastify-1000px-square-01.svg
- fastify-1000px-square-02.png
- fastify-1000px-square-02.svg

have the BG color black and white and not transparent.

Sorry for the silly request, but I don't have software to edit the `.ai` file
cc @lmammino 

Here a preview:

image

https://github.com/Eomm/artwork/tree/fastify#fastify

### PR DESCRIPTION
**Pull request by Eomm**
Fix #5

### CODE REVIEW

**Comment by Eomm** [comment]
cc @mcollina

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Eomm** [comment]
Friendly ping @lmammino 🙏🏽

**Comment by Eomm** [comment]
@mcollina would you mind to merge it?

**Comment by lmammino** [comment]
wow sorry totally missed your ping months ago :(

**Pull request merged**
